export { default as NavBar } from "./NavBar";
export { default as Introduction } from "./Introduction";
export { default as WDev } from "./WComponents/WDev";
export { default as WMes } from "./WComponents/WMes";
export { default as Projects } from "./Projects";
export { default as Project } from "./Project";
export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as Input } from "./Input";
